export const GET_ZIP_CODE = 'GET_ZIP_CODE';
export const GET_LOCAL_TIPS = 'GET_LOCAL_TIPS';
export const TOGGLE_ADD_TIPS_BUTTON = 'TOGGLE_ADD_TIPS_BUTTON';
export const UPVOTE = 'UPVOTE';
export const DOWNVOTE = 'DOWNVOTE';
export const INPUT_HEADER ="INPUT_HEADER";
export const INPUT_BLURB = "INPUT_BLURB";
export const INPUT_LOCATION = "INPUT_LOCATION";
export const TOGGLE_TAGS_DROPDOWN = "TOGGLE_TAGS_DROPDOWN";

//REDUX-THUNK:
export const START_FETCHING_TIPS = "START_FETCHING_TIPS";
export const FETCHING_TIPS = "FETCHING_TIPS";
export const POST_TIP = "POST_TIP";
export const ADD_TIP = "ADD_TIP";
export const START_FETCHING_TAGS = "START_FETCHING_TAGS";
export const FETCHING_TAGS = "FETCHING_TAGS"

//TAGS
export const SELECT_TAG = "SELECT_TAG";
export const FILTER_TIPS_BY_TAG = "FILTER_TIPS_BY_TAG";
export const ASSIGN_TAG = "ASSIGN_TAG";

//FOR DEVELOPMENT ONLY
export const GET_DUMMY_TIPS = 'GET_DUMMY_TIPS';
