export const GET_ZIP_CODE = 'GET_ZIP_CODE';
export const GET_LOCAL_TIPS = 'GET_LOCAL_TIPS';
export const TOGGLE_ADD_TIPS_BUTTON = 'TOGGLE_ADD_TIPS_BUTTON';
export const UPVOTE = 'UPVOTE';
export const DOWNVOTE = 'DOWNVOTE';
export const INPUT_HEADER ="INPUT_HEADER";
export const INPUT_BLURB = "INPUT_BLURB";
export const INPUT_LOCATION = "INPUT_LOCATION";
export const TOGGLE_TAGS_DROPDOWN = "TOGGLE_TAGS_DROPDOWN";

//REDUX-THUNK:
export const START_FETCHING_TIPS = "START_FETCHING_TIPS";
export const FETCHING_TIPS = "FETCHING_TIPS";
export const POST_TIP = "POST_TIP";
export const ADD_TIP = "ADD_TIP";
//FOR DEVELOPMENT ONLY
export const GET_DUMMY_TIPS = 'GET_DUMMY_TIPS';
